config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
    root 'posts#index'

    resources :user, :only => [:new, :create, :destroy]
    resources :sessions, :only => [:new, :create, :destroy]
    match '/signup', :to => 'users#new', via: :get
    match '/signin', :to => 'sessions#new', via: :get
    match '/signout', :to => 'sessions#destroy', via: :delete

    get 'base/login'
    post 'base/loginattemp'
    post 'base/forgotpassword'
    resources :posts
    resources :games
    resources :categories, except: [:show]
    resources :uploads, only: [:index, :show, :update, :create]
    resources :settings, only: [:index, :edit, :update]
  end

  get 'site/index'
  get 'site/botiafriends'
  get 'site/whenaliensolvemath'
  get 'site/cleanadventure'

  root 'site#index'

end

app/models/admin/game.rb
class Admin::Game < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action :set_admin_game, only: [:show, :edit, :update, :destroy]

  # GET /admin/games
  # GET /admin/games.json
  def index
    @admin_games = Admin::Game.all
  end

  # GET /admin/games/1
  # GET /admin/games/1.json
  def show
  end

  # GET /admin/games/new
  def new
    @admin_game = Admin::Game.new
  end

  # GET /admin/games/1/edit
  def edit
  end

  # POST /admin/games
  # POST /admin/games.json
  def create
    @admin_game = Admin::Game.new(admin_game_params)

    respond_to do |format|
      if @admin_game.save
        format.html { redirect_to @admin_game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @admin_game }
      else
        format.html { render :new }
        format.json { render json: @admin_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/games/1
  # PATCH/PUT /admin/games/1.json
  def update
    respond_to do |format|
      if @admin_game.update(admin_game_params)
        format.html { redirect_to @admin_game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_game }
      else
        format.html { render :edit }
        format.json { render json: @admin_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/games/1
  # DELETE /admin/games/1.json
  def destroy
    @admin_game.destroy
    respond_to do |format|
      format.html { redirect_to admin_games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_game
      @admin_game = Admin::Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_game_params
      params.require(:admin_game).permit(:name, :description)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description)
    end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/admin/games/_form.html.erb
<%= form_for(@admin_game) do |f| %>
  <% if @admin_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_game.errors.count, "error") %> prohibited this admin_game from being saved:</h2>

      <ul>
      <% @admin_game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/games/edit.html.erb
<h1>Editing Admin Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_game %> |
<%= link_to 'Back', admin_games_path %>

app/views/admin/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_games.each do |admin_game| %>
      <tr>
        <td><%= admin_game.name %></td>
        <td><%= admin_game.description %></td>
        <td><%= link_to 'Show', admin_game %></td>
        <td><%= link_to 'Edit', edit_admin_game_path(admin_game) %></td>
        <td><%= link_to 'Destroy', admin_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_admin_game_path %>

app/views/admin/games/new.html.erb
<h1>New Admin Game</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_games_path %>

app/views/admin/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_game.description %>
</p>

<%= link_to 'Edit', edit_admin_game_path(@admin_game) %> |
<%= link_to 'Back', admin_games_path %>