config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
    root 'posts#index'

    resources :user, :only => [:new, :create, :destroy]
    resources :sessions, :only => [:new, :create, :destroy]
    match '/signup', :to => 'users#new', via: :get
    match '/signin', :to => 'sessions#new', via: :get
    match '/signout', :to => 'sessions#destroy', via: :delete

    get 'base/login'
    post 'base/loginattemp'
    post 'base/forgotpassword'
    resources :posts
    resources :games
    resources :categories, except: [:show]
    resources :uploads, only: [:index, :show, :update, :create]
    resources :settings, only: [:index, :edit, :update]
  end

  get 'site/index'
  get 'site/botiafriends'
  get 'site/whenaliensolvemath'
  get 'site/cleanadventure'

  root 'site#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    protect_from_forgery
    layout 'admin'

    protected
        # Returns the currently logged in admin or nil if there isn't one
        def current_admin
            return unless session[:admin_id]
            @current_admin ||= AdminLogin.find_by_id(session[:adminr_id]) 
        end


    public
        # GET /admin/post/index
        def index
            @posts = ::Post.all
        end

        # GET /admin/post/new
        def new
            @post = ::Post.new
        end

        # GET /admin/post/<id>/edit
        def edit
        end

        # POST /admin/post
        # POST /admin/post.json
        def create
            @post = Post.new(post_params)

            respond_to do |format|
            if @post.save
                format.html { redirect_to admin_posts_url, notice: 'Post was successfully created.' }
                format.json { render :show, status: :created, location: @post }
            else
                format.html { render :new }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
            end
        end

        # PATCH/PUT /admin/games/1
        # PATCH/PUT /admin/games/1.json
        def update
            respond_to do |format|
            if @post.update(post_params)
                format.html { redirect_to @post, notice: 'Game was successfully updated.' }
                format.json { render :show, status: :ok, location: @post }
            else
                format.html { render :edit }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
            end
        end

        # DELETE /admin/games/1
        # DELETE /admin/games/1.json
        def destroy
            @post.destroy
            respond_to do |format|
            format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
            format.json { head :no_content }
            end
        end

    private
        def not_authenticated
            redirect_to login_path, alert: "Please login first"
        end

        # Use callbacks to share common setup or constraints between actions.
        def set_post
            @post = ::Post.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def post_params
        params.require(:post).permit(:title, :post)
        end
end

app/views/admin/posts/_form.html.erb
<div class="content">

  <%= form_for(@post, :url => admin_posts_path) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, {:class => 'form-control', :placeholder => 'Title'} %>
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :post %><br>
          <%= f.text_area(:post, {:rows => '5', :class => 'form-control', :placeholder => 'Some Text About Post'}) %>
        </div>
      </div>
    </div>

    <%= f.submit({:class => 'btn btn-info btn-fill pull-right'}) %>
    <div class="clearfix"></div>

  <% end %>
</div>

app/views/admin/posts/edit.html.erb
<div class="row">

    <div class="col-md-12">
      <div class="card card-plain">
        <%= link_to 'Show', admin_post_path(@post), {:class => 'btn btn-default'} %>
        <%= link_to 'Back', admin_posts_path, {:class => 'btn btn-default'} %>
      </div>

      <div class="card">
          <div class="header">
              <h4 class="title">New Post</h4>
              <p class="category">Create new post</p>
          </div>
          <%= render 'form' %>
      </div>
    </div>

</div>

app/views/admin/posts/index.html.erb
<% content_for :headnav do %>
  <a class="navbar-brand" href="#">Post</a>
<% end %>


<% if !notice.nil? %>
  <div class="alert alert-info">
      <span><%= notice %></span>
  </div>
<% end %>

<div class="row">

    <div class="col-md-12">
      <div class="card card-plain">
        <%= link_to 'New Post', new_admin_post_path, {:class => 'btn btn-default'} %>
      </div>

      <div class="card">
          <div class="header">
              <h4 class="title">Listing Posts</h4>
              <p class="category">All your posts</p>
          </div>
          <div class="content table-responsive table-full-width">
              <table class="table table-hover table-striped">
                  <thead>
                    <tr><th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Action</th>
                  </tr></thead>
                  <tbody>
                    <% @posts.each do |post| %>
                      <tr>
                        <td>0</td>
                        <td><%= post.title %></td>
                        <td><%= post.post %></td>
                        <td>
                          <%= link_to admin_post_path(post), {:title => 'View', :rel => 'tooltip', :class => 'btn btn-info btn-simple btn-sm'} do %> 
                            <i class="fa fa-eye"></i>
                          <% end %>

                          <%= link_to edit_admin_post_path(post), {:title => 'Edit', :rel => 'tooltip', :class => 'btn btn-info btn-simple btn-sm'} do %> 
                            <i class="fa fa-edit"></i>
                          <% end %>

                          <%= link_to admin_post_path(post), {:title => 'Remove', :rel => 'tooltip', method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-simple btn-sm'} do %> 
                            <i class="fa fa-times"></i>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>

          </div>
      </div>
    </div>


    <div class="col-md-12">
      <div class="card card-plain">
        <%= link_to 'New Tags', new_admin_post_path, {:class => 'btn btn-default'} %>
      </div>

      <div class="card">
          <div class="header">
              <h4 class="title">Listing Tags</h4>
              <p class="category">All your post tags</p>
          </div>
          <div class="content table-responsive table-full-width">
              <table class="table table-hover table-striped">
                  <thead>
                    <tr><th>ID</th>
                    <th>Name</th>
                    <th>Action</th>
                  </tr></thead>
                  <tbody>
                    <% @posts.each do |post| %>
                      <tr>
                        <td>0</td>
                        <td><%= post.title %></td>
                        <td>
                          <%= link_to admin_post_path(post), {:title => 'View', :rel => 'tooltip', :class => 'btn btn-info btn-simple btn-sm'} do %> 
                            <i class="fa fa-edit"></i>
                          <% end %>

                          <%= link_to edit_admin_post_path(post), {:title => 'Edit', :rel => 'tooltip', :class => 'btn btn-info btn-simple btn-sm'} do %> 
                            <i class="fa fa-edit"></i>
                          <% end %>

                          <%= link_to admin_post_path(post), {:title => 'Remove', :rel => 'tooltip', method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-simple btn-sm'} do %> 
                            <i class="fa fa-times"></i>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>

          </div>
      </div>
    </div>
</div>

app/views/admin/posts/new.html.erb
<div class="row">

    <div class="col-md-12">
      <div class="card card-plain">
        <%= link_to 'Back', admin_posts_path, {:class => 'btn btn-default'} %>
      </div>

      <div class="card">
          <div class="header">
              <h4 class="title">New Post</h4>
              <p class="category">Create new post</p>
          </div>
          <%= render 'form' %>
      </div>
    </div>

</div>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

    <div class="col-md-12">
      <div class="card card-plain">
        <%= link_to 'Edit', edit_admin_post_path(@post), {:class => 'btn btn-default'} %>
        <%= link_to 'Back', admin_posts_path, {:class => 'btn btn-default'} %>
      </div>

      <div class="card">
          <div class="header">
              <h4 class="title">Listing Posts</h4>
              <p class="category">All your posts</p>
          </div>
          <p>
            <strong>Name:</strong>
            <%= @post.title %>
          </p>

          <p>
            <strong>Description:</strong>
            <%= @post.post %>
          </p>
      </div>
    </div>