config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
    root 'posts#index'

    resources :user, :only => [:new, :create, :destroy]
    resources :sessions, :only => [:new, :create, :destroy]
    match '/signup', :to => 'users#new', via: :get
    match '/signin', :to => 'sessions#new', via: :get
    match '/signout', :to => 'sessions#destroy', via: :delete

    get 'base/login'
    post 'base/loginattemp'
    post 'base/forgotpassword'
    resources :posts
    resources :games
    resources :categories, except: [:show]
    resources :uploads, only: [:index, :show, :update, :create]
    resources :settings, only: [:index, :edit, :update]
  end

  get 'site/index'
  get 'site/botiafriends'
  get 'site/whenaliensolvemath'
  get 'site/cleanadventure'

  root 'site#index'

end

app/models/admin/user.rb
class Admin::User < ActiveRecord::Base
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin_login'

  def new
    @title = "Sign up"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      # Handle a successful save.
    else
      @title = "Sign up"
      render 'new'
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/new.html.erb
<div class="content">
    <!-- BEGIN LOGIN FORM -->
    <%= form_for(:admin_login, :url => admin_sessions_path) do |f| %>
        <h3 class="form-title">Sign Up</h3>

        <% if !alert.nil? %>
            <div class="alert alert-danger hiddden">
                <button class="close" data-close="alert"></button>
                <span>
                Enter valid username and password. </span>
            </div>
        <% end %>

        <div class="form-group">
            <div class="field">
                <%= f.label(:email) %><br>
                <%= f.email_field(:email, :class => 'form-control placeholder-no-fix') %>
            </div>
            <div class="field">
                <%= f.label(:password) %><br>
                <%= f.password_field(:password, :class => 'form-control placeholder-no-fix') %>
            </div>
        </div>
        <div class="form-actions">
            <%= check_box_tag(:remember_me) %>
            <%= label_tag(:remember_me, "remember me") %>
            <%= f.submit(:login, :class => 'btn btn-success', :name => 'submit-button') %>
            <a href="javascript:;" id="forget-password" class="forget-password">Forgot Password?</a>
        </div>
    <% end %>
</div>